; Python Built-ins

(abs)
(all)
(any)
(ascii)
(bin)
(breakpoint)
(callable)
(chr)
(compile)
(delattr)
(dir)
(divmod)
(eval)
(exec)
(format)
(getattr)
(globals)
(hasattr)
(hash)
(hex)
(id)
(input)
(isinstance)
(issubclass)
(iter)
(aiter)
(len)
(locals)
(max)
(min)
(next)
(anext)
(oct)
(ord)
(pow)
(print)
(repr)
(round)
(setattr)
(sorted)
(sum)
(vars)
(None)
(...) (Ellipsis)
(NotImplemented)
(False)
(True)
(bool)
(memoryview)
(bytearray)
(bytes)
(classmethod)
(complex)
(dict)
(enumerate)
(filter)
(float)
(frozenset)
(property)
(int)
(list)
(map)
(object)
(range)
(reversed)
(set)
(slice)
(staticmethod)
(str)
(super)
(tuple)
(type)
(zip)
(open)
(quit)
(exit)
(copyright)
(credits)
(help)

; Hy Macros
(eval-and-compile) (eval_and_compile)
(eval-when-compile) (eval_when_compile)
(do) (do_mac)
(py)
(pys)
(pragma)
(quote)
(quasiquote)
(not)
(~) (bnot)
(and)
(or)
(!=) (hyx_Xexclamation_markXXequals_signX)
(is-not) (is_not)
(in)
(not-in) (not_in)
(=) (hyx_Xequals_signX)
(is)
(<) (hyx_XlessHthan_signX)
(<=) (hyx_XlessHthan_signXXequals_signX)
(>) (hyx_XgreaterHthan_signX)
(>=) (hyx_XgreaterHthan_signXXequals_signX)
(chainc)
(%) (hyx_Xpercent_signX)
(~) (hyx_Xcircumflex_accentX)
(*) (hyx_XasteriskXXasteriskX)
(//) (hyx_XsolidusXXsolidusX)
(<<) (hyx_XlessHthan_signXXlessHthan_signX)
(>>) (hyx_XgreaterHthan_signXXgreaterHthan_signX)
(-=) (hyx_XhyphenHminusX)
(/) (hyx_XsolidusX)
(&) (hyx_XampersandX)
(@) (hyx_Xcommercial_atX)
(+) (hyx_Xplus_signX)
(*) (hyx_XasteriskX)
(|) (hyx_Xvertical_lineX)
(%=) (hyx_Xpercent_signXXequals_signX)
(~=) (hyx_Xcircumflex_accentXXequals_signX)
(+=)(hyx_Xplus_signXXequals_signX)
(/=) (hyx_XsolidusXXequals_signX)
(//=) (hyx_XsolidusXXsolidusXXequals_signX)
(*=) (hyx_XasteriskXXequals_signX)
(--=) (hyx_XhyphenHminusXXequals_signX)
(**=) (hyx_XasteriskXXasteriskXXequals_signX)
(<<=) (hyx_XlessHthan_signXXlessHthan_signXXequals_signX)
(>>=) (hyx_XgreaterHthan_signXXgreaterHthan_signXXequals_signX)
(|=) (hyx_Xvertical_lineXXequals_signX)
(&=) (hyx_XampersandXXequals_signX)
(@=) (hyx_Xcommercial_atXXequals_signX)
(setx)
(setv)
(let)
(annotate)
(deftype)
(global)
(nonlocal)
(del)
(get)
(.) (hyx_Xfull_stopX)
(cut)
(#*) (unpack-iterable)
(if)
(dfor)
(lfor)
(sfor)
(gfor)
(for)
(while)
(break)
(continue)
(with)
(match)
(raise)
(try)
(fn)
(defn)
(defmacro)
(return)
(yield)
(await)
(defclass)
(require)
(import)
(assert)
(unquote)
(~@) (unquote-splice)
(#**) (unpack-mapping)
(except)
(except*) (hyx_exceptXasteriskX)
(finally)
(else)
(cond)
(when)
(defreader)
(get) (get_macro)
(local-macros) (local_macros)
(export)